#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA5bz4JUC93ngz+sCtwDYro7EhkPq4DyBtn4f47uTZEmfzbAou
    SYc8jSbA4bYn6Fm5E/AMlLsjWs52PKYU7UD3fLjXLGxMSSxHXH/r6UhaEMDjQGHb
    3Q/NbL9HtzlaBbMmDzaaf8mvmYNixhBgqSax2Rm4OWX0hqi+1joYcFXmJkNzUPLQ
    yzwpwQblX/pc2q1j4lccK3VU7Cesg69a3sJFW3lQ3r5PP3R2XciMpRTfhbLZSztm
    G+EWTL9FXpvKRyPwdQMSiakQOAiRw8vHT7mXwg4nYGguKc0aMnTcQ4DeZO6i/Jlg
    J3wHMvXfbXzXVmWMzyct2gQVVhs6Ov/iEaIkQQIDAQABAoIBAAW13cEnS9Dk0f3w
    niEB97G47GmrIboWh0MI4TIm9BJWDSHpWt8vAl1L0k2J9pH68PPC6r0jraxLJ3s4
    cZq4G6649XhANOE4vYlaEKYay0pRURS/mfRzuRpz4rd2MHulyVNlew+kFr5NGr5r
    l8t8j70iu4aJtztFpIC0rvjT2cWnqXupMF3zIPLKBD7ZAeOgKaj1ZBi2Y58BCjU3
    WObMvylbEuUVyzFDE/lV+sSBASa+lTU9a6IMY4ixdt+CPEZe51buUX+U7lC4KVR7
    vY/U/eZLz4myIvGDpKHrtYkZK0rN0AfvtSCwFej6NYGylQLc7ljbgrU2yNAe8M7z
    mZIGn3ECgYEA/aCe3pyf3MOJ8KOtcjZ9IMWOeaxFPVh/5KvUkMwD2piYuQ3bTvE/
    cZ6DXmoFp+iO399Yp2EkttDdm6bjBevFyKJvJVYi+Vo3Pk6NLWPGZCVZdR3Rm1ZN
    tAcdNyzomfMhGvmb8s3ojT+WovYNMXUkCpspYq9WiSsabZk1DM40a8UCgYEA5+Mj
    sjMXDVtQKY9QusSNuPUEL8KHkrjL5GePpwFa8jW32fOqikafDw3adVgrFlZOkeLo
    bCayEQ1nd5csnyyCMFWyMHpU6sMG6C3i+Yl8b+nBc6JYPbRyVRu7DNauNQxENOr8
    oZ6IOYI0QftFu/flEgeybdynQdmjJek7bcJgck0CgYA1SS63pH5tumNbvHevXEVT
    wk3ZwFjXt6U/HN7PAR36Kj9D+eZOop7qtxvwlSPVECYcYOdWWzGEe0Nj9V8TGmL2
    cTIazQsSCmM64vQESkcfOT2fPoGQOkSfAzOfKP9BgPQ+n5ylGZ+3NVnnqPxCnNLS
    q6C5TA9JSFYIGr0rkJMw5QKBgQCG7oXb8JyuWf8YX9uTAkKRaIlqHSD0gHGsU5Kk
    lEZOgHGd8oq+8X8mrGH9PDO+SLRpcYbbP90HzSvyy9XcPXL4GzWXvedhv+BqBCF6
    IMV2/adi2QnNxg1tdrhuLRGrrpqVzFL63JvaEujDqCoYyZPS3QW3pdjxmWm06rV5
    Fc03VQKBgQCwRCQPqG0iKjsX3gysJIrhzvpxadgFdoLPaU5Ji9CTDKdij4Hhc0zm
    i+NP9ktFed0nfnKkHQlWMybPT7vgJFsGZgiWZR31HiCzu3vgGudZhdC0qtBizNqP
    d8ASUxlhacCwHeB5Q4VJAI6AM80Ae8lERUL25x6apLa3g2IFnDBr8w==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['RELEASE_KEY1'] %>"
      iv:                "7M47eZd/EWqMkqwuQOF+2Q=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA6M0fCDl9KDjn8hIyKvzhu5TwyqAE3PIPNKRhXA3nXaubW2jM
    N6yYrWcKc3rWIiGbJAY+BYbd2hDi0DtJZuWEkrGMUPjWxYVtL4ZdE3qb+74v9LFk
    7s4zfTbhFylgWZPjM85sV5zZ88JUsYkjFlIYXMJrPVsPBmP5ENzgkGTguIQZyxCe
    zOsbdOO0fIyadyQKqytppVXoZls8y16OkEy6wdDJ+3eJQFyp+m6oA9bNz35qz036
    ga+iF+3RCAgXEvN+Zd+UUCWhb0NzoOcJT/5jmH6LXrJUAbt1AQD3gX+tSu6R31+e
    1CN5rKnNAN6tu2H4W/Hco81HwabZYKr6T8C7hwIDAQABAoIBAQDLZzU+7WPyOc5G
    zikxMCRWziqZD7lQBtrMRveeA7PsPt0NwAH2fwIjN82E2oWv6qbvkdis4YqDVo+m
    GrbmhZEQzrpnoROeHxcoGADI3S7ehOzHohsrH9UTCVkf8JHzkmhIQoqc/jncZiWz
    vLuAbBhHK8OhJyd4kO70EdjPsKQ78dzsrS42Pt8fTM3pGADeJfrvFBzQJ72wAmBW
    b4+iqALD+VZ/5WlkYJK89VIXNguDXZk/oIETkrsolXk1Q/YsEc1Odal118Ulvyvx
    SUluaFiW/Ff0Gt7MkphHVGmnWan4GLzQT9YM6Oas6Y+V9bOHcvJ4CS8WA1xeN8/u
    YRnECtN5AoGBAPz1LlkA0WNF3IDVfnp8afirkYlqKuxGC+zpDuiVAPDeerlrlTll
    xFIYY0z66kHCcRzLhpA686+GeGM4j/GCyqHiqTXwIJLiudrMKlpeOuk5GaFfXM3w
    hjjWHan9zQ5025EPXAL2m+u1u30eQWvNFlT23++AGOfSQETMDYh5P7ItAoGBAOuZ
    4aJCcgvrktzgKRjf671zoogiN/bUWM5vIahJncjubXwgncGM9wv8K9OU+7eznS4N
    ZGcSB37eOkuQywPEvqlNpyFkRl7Cz6DZeHX9Ai9TNQvCMDYQxcQtXtx1gZICvQfq
    lv/HabNgb2u6DMGLH31qcgd3hTThEjUlmyH1UFkDAoGAXjOYXQDW+VdM9JWNEmQ+
    uqJ6AmiNL4wuaL2qFadXwFu57E9KNSPW5pO6dzKCBpc4tHZ+2Dt8AIPdVWX9BP2m
    JH9acIHKP6k7eWXK5/hri+r9xoDS+MZ31ba3OVURBi8yjWTg6SGZk0AMYF3iExk/
    FckSQAi+Paao1HYBHC+7LskCgYADHA/XVWst7xkMI0VHl8UDxh/yDgmRD3JwnxTh
    pL8ZZNQ7HC8Y2+Ry2ww1CbVc0lkTv4eAuMMykHpSfwG+9fzSPT0keq9XFtkotVYa
    sJEz0LRViGWcgRIrKbIj1MU2CSU3kogVrisd+/rcgCMk9tIelKYWpSQz83iLDQkE
    JLm/wwKBgQCUyfYJG9/Tzt8yxeLKTMpc9bG/PHJikfN6vEOa5GwK5/ZYDj8RE2Iw
    dtpGMw3457+hvVLUjiPL4SQ5l14flWpd1Lg00FU8xvk+TnRhXOFPbl6LJr2enw4+
    18BpY1Mx6fxjxj4XIpIhb752F8JeV74OH9yJscX2tWyIkZQXN1hnwg==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:                "X0GPGwkUziT7CACJK+Gksw=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
