#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:
  key:               " \xDE\x8A\x1DN\xB4y\x8A'l\xD1\b-\xD2.w"
  iv:                "9\xF2\x7F\x85/:\\\x1A,\xDE\xAD\x14h\xC1(\xB6"
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  key:               "\x00\x1Cn^EDR\x80Q\x81p\e\xED\x88N\x80"
  iv:                "\xF5\xE4\xF6\xD0\x89K\x06\x87\x02!p\x05E\x02\xC0\xA6"
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAxuOMKpK0j9mx5PwUn2xHv2MENLTSpwRnl2T9OKfrHiKlcxFj
    BuuzIFcTLH+7aklWZQbXWftTSQKD8iTS5Yyv40Rv2V4WUgWa0YmaZOE4jnq10ABM
    iN4AcUlzbXkoa9e+hRSykCRPT42BM93fAFtyt0SfXXXa0nA4qZSFp1t1VlUabEl8
    QjWVSpb66XBQR43iJoMZKdynuVUpE/GLtJKEJh6V9AjVzvnHst6932lxwl315O1Y
    6U8fi3yMG7K/hsNKZ+ZJXjjhF/ZoRSgqfv585WH4AhfhaBwlItA9u8UpU3GDoREK
    foQXufDCjhGPMw7Kr6ATM+RqX9cdzvQNKIMECQIDAQABAoIBAQCS1vlrjTjmY/Gl
    gD+xnH40XWSDjWVhjiz1Z8hVBhTfAPFqTVHxkB+GJwOu/Pdf95ljqXNhqd7JrqPA
    KVPTytUpVCPINmEAWcb+ITvucyIQf6SwVygqfM2S1on0L1malYTCOI/FQCmWMIFN
    y+eTGfFOQcnvdM4ERHpxKYisEShGfeyzkd5b6rk5Lj8XgMzLJ6PKf48DkJlUwmSE
    6ZtmgKYbtnWncyLhTXcetS8Xbv+tT2t6grIvPNg9Z+pBMSRJkcC5MMdcf7yipvTm
    pGU/E+FH1uz2vuq42q8HoLt7wPjmJk0eM3Kb7AIXzplv/102eaTP15eeiqhDWeBD
    HOPYVg6JAoGBAPGxlCmLXWzpnteyA/HjYpiFUv+jpZeRcoqx8a/Fcjjsj6wwEQX6
    Ju5+OgkeOZ8E7XIpM9/lrWUwsD6q3308PuS4JXjh0zV6dJ+Q88pRmK8jzQl0Sizp
    ODvckwKN5Je8wksrB4HP3/3dj0lFjHRygMTbJauHySfEN8aCx26NVgyrAoGBANKp
    V0ZCx6plJCfMtW7TIAuD2/UmQ3BVyiBL5NUGE8s1AVMQLtLdrbcp7ue2VGMib1CP
    qXLTBm9/0nkt2NlJT4e2PgioH/7LgdmP/4gq+qcf1KvGfVn1/+ZtILKGtQWm5k/l
    iEPfoWRd39fIvkJ/VgSt5/rh5thr+Q26rqFZ0wobAoGAbMVUPpYfx4IkIEJXECcb
    GjT2M2I8hcfJWq3WbRpY21FrHzzKjHwVxUM9bxkRKYWYLsZoOB0vOdj9mFZiGgRg
    8aIGCy7mVKz1i1I6xRSPuFJOVjDlqOyUiCwuZPnipH8omZeV20/oKGHruDf6i/V0
    CiPuAhIr7x+ZUldM1W36Cd0CgYEAgwgJ3Q4Um4wlnQvbnn974y21Vxrhv7Hc85HB
    WC9biH4DwOLD/S0drFxM2ZuziaYVjwqM33sa+aeMBwvZYe4TpdpZY5EPtbBnqCfF
    TbFODz3hTqc7uQUmkvE18VWQq19Qykl/JJipDoDFhra6gSorGuYA8TAqIlumoj+H
    95yjhBkCgYEA4YVdVL3Mn83HtxTtJuVmnD4e0O+xQpIBB7Bo21CHXVQlz0c0L35U
    OOzf4d6UGBSjtFlUFOo1k2iWId9w7DO+UJycmr0x62raVbD3V53vepLC0smhIFsk
    2rzSDbDRc2uNcdoM74qUuaHNM5UdeKo98Q6q7+/z5pYLVyoCdtmM39A=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /etc/rails/keys/griffen_release.key
      iv_filename:       /etc/rails/keys/griffen_release.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA+AjYkEX7sH2Gfif7skNMvwRx5FHn1lrgqXQG+jbfCk6pMAHb
    0VpB2C2bPvE4ebi5A21P7tPTGgcSF8ViJb68wtaH1z6vr6M6xRNtYekkwJrjTxO5
    LS9zvyBKVE6dEZvgnE88hJYia73F3B+3FjcYT9Az9mg7+IY+gWkHPECN31EG3Ay8
    SC2alk7iwzcrtO9/LAi6f0UFFfqBiEj7yDpWm9pHrMPzwSj3T5KmsZ489cxec2lj
    uc4tsZa0BDGL7b/+Xm1XFnRjc8ezDt/a3xq5baYdxMjMtFg35ko5ZVefwmM9K9sc
    C7eJzzlocPPcOwqqh9bukAVk9dlQPQWgCCCs9QIDAQABAoIBAQDyqvzuknm/39/Q
    19+KNgwFKx0ey/+uGbWKNImLDlpDZFhlLrxY5Bxdm6ky+KBPfqoMr0swF7CG23oZ
    JbVzxlw5p9i5f4w1o9ag7/PpgkfB5QgV2u8mRTHSQY5XU56als43P9KuyZCdpsrJ
    JYJkSr0PgV0FbE+YRActZ4t7qJDldRzTOqoJoxymqtJQPBH2KsnOldiYj0QuURCt
    wex+aila6PVwpIKTLRcvmYc+bHLMMczxpyR2IBJrmYtpz5BTCsJPslcQu/c4PVBx
    X8T8rmbkFLQiD1bRIFLiSdubuLib2u70hbMDzmoWURdn2mfIK/5MshYYNzZtxwFh
    OOuwKx0hAoGBAP0+xF0OWrWNEVEGKX8mRrgIVNk2q+CH1PbYUpiKoILksUK8Zg2Z
    59hwiaLOtVaZJZVEhGPbHlpfa7KDSKxWCoQK104rIBOlTb7bSzKuk52oVmEpTZhU
    SxXi0bO3Lw2dZEe3FTDF644IbjMt2Ewa/QuSvA/KYO1go1BIPo6zxeUtAoGBAPq7
    kYTWtypCoL617NWWiJ0hz8JrWqj2da9LxjprTyy70X0X1m0SXNDOPVWjeA2DuXZs
    WhbdtN2szr7Qavyn+W0Ty0jna6UA2Tzudt/64s2+8uyptoG+160cyvD8iRHz22z2
    0A3VmIDvHC/EwV9FDaWhWeTT29l9JVy08GlC+9PpAoGAFfux3gYV97aULz1issfm
    0ajffK+TQf1ojjj/CoDWKCakAJAMJ9gZWR+Dwx9AfJD0wz1cZLKrstqfpbJhx5v8
    c7PhNsbllO7/jbbJk0+2PrRTM0H7m2KN1guHeptHOV5VSyhobYBwzzaKImUzZn/d
    QXjuXEyMF28RHjH3RDn0zs0CgYAISWa30zjehrE1XGHldUIyn0l0jYPDjdG553E3
    wRAu1E5KKh2GIVM7+3T/fZWcLLxWc6JOmyk9Ilb663x9uTd/KWZQlIV0QKDtaJw5
    LtuMHUF+HOXRR/Ns30S9zjrhgwO/iDC8JFEUAdMWqRQTB/85eCm2bGIZwA8aD0ja
    0cHs8QKBgGaULsfYmNXq3xpE/zcgfluUwIUUWvRz2hU6mwv5R9QBYRHmIlqvZpZ1
    h5J6AFKI8/XhbzZWMRsyQWUAA6N2xg1eo6f82+P/XOs7toyHZ6ZimGZuNzuWqwcB
    5nGCJ6e34nxf4+Htji3hqp89BjRltG+A1UejICLv7wzmCbJmVRe/
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /etc/rails/keys/griffen_production.key
      iv_filename:       /etc/rails/keys/griffen_production.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
