require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ApplicationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Application. As you add validations to Application, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { @application = create(:application) }

  let(:invalid_attributes) { @application = create(:application, traits: [:invalid]) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApplicationsController. Be sure to keep this updated too.
  let(:valid_session) { @user = create(:user) }

  describe "GET #index" do
    # Sign in an admin to see Applications Index page
    before(:each) do
      @admin = create(:admin)
      sign_in @admin
    end

    it "assigns all applications as @applications" do
      application = create(:application)
      get :index
      expect(assigns(:applications)).to eq([application])
    end

    it "renders the :index view" do
      get :index
      expect(response).to render_template :index
    end
  end

  # Sign in a user for the rest of the tests
  before (:each) do
    @user = create(:user)
    sign_in @user
  end 

  describe "GET #show" do
    it "assigns the requested application as @application" do
      application = create(:application)
      get :show, id: application
      expect(assigns(:application)).to eq(application)
    end

    it "renders the :show view" do
      get :show, id: create(:application)
      expect(response).to render_template :show
    end
  end

  describe "GET #new" do
    it "assigns a new application as @application" do
      get :new
      expect(assigns(:application)).to be_a_new(Application)
    end

    it "renders the :new view" do
      get :new
      expect(response).to render_template :new
    end
  end

  describe "GET #edit" do
    it "assigns the requested application as @application" do
      application = create(:application)
      get :edit, id: application
      expect(assigns(:application)).to eq(application)
    end

    it "renders the :edit view" do
      application = create(:application)
      get :edit, id: application
      expect(response).to render_template :edit
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Application" do
        expect {
          post :create, application: attributes_for(:application)
        }.to change(Application, :count).by(1)
      end

      it "assigns a newly created application as @application" do
        post :create, application: attributes_for(:application)
        expect(assigns(:application)).to be_a(Application)
        expect(assigns(:application)).to be_persisted
      end

      it "redirects to the user profile" do
        post :create, application: attributes_for(:application)
        expect(response).to redirect_to(@user)
      end
    end

    context "with invalid params" do
      it "does not save the new application" do
        expect {
          post :create, application: attributes_for(:application, :invalid)
        }.to_not change(Application, :count)
      end

      it "assigns a newly created but unsaved application as @application" do
        post :create, application: attributes_for(:application, :invalid)
        expect(assigns(:application)).to be_a_new(Application)
      end

      it "re-renders the 'new' template" do
        post :create, application: attributes_for(:application, :invalid)
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    before(:each) do
      @application = create(:application, oname: "Larry Smith")
    end

    context "with valid params" do
      it "locates the requested @application" do
        put :update, id: @application, application: attributes_for(:application)
        expect(assigns(:application)).to eq(@application)
      end

      it "updates the requested application" do
        put :update, id: @application, application: attributes_for(:application, 
          oname: "Jimmy Bones", legalname: "Bones' Bongs")
        @application.reload
        expect(@application.oname).to eq("Jimmy Bones")
        expect(@application.legalname).to eq("Bones' Bongs")
      end

      it "redirects to the user profile" do
        put :update, id: @application, application: attributes_for(:application)
        expect(response).to redirect_to(@user)
      end
    end

    context "with invalid params" do
      it "locates the requested @application" do
        put :update, id: @application, application: attributes_for(:application, :invalid)
        expect(assigns(:application)).to eq(@application)
      end

      it "does not change @application's attributes" do
        put :update, id: @application, application: attributes_for(:application, :invalid)
        @application.reload
        expect(@application.oname).to_not eq("Jimmy Bones")
      end

      it "re-renders the 'edit' template" do
        put :update, id: @application, application: attributes_for(:application, :invalid )
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    before(:each) do
      @application = create(:application)
    end

    it "deletes the @application" do
      expect {
        delete :destroy, id: @application
      }.to change(Application, :count).by(-1)
    end

    it "redirects to the user profile" do
      delete :destroy, id: @application
      expect(response).to redirect_to(@user)
    end

    it "redirects to the applications #index" do
      @admin = create(:admin)
      sign_in @admin
      delete :destroy, id: @application
      expect(response).to redirect_to applications_url
    end
  end
end















